DESCRIPTIONS = {
    "minimal": {
        "get_shape": "Returns shape of dataset.",
        "get_missing_values": "Returns missing value information.",
        "get_dtypes": "Returns the type of data.",
        "get_cardinality": "Returns unique value counts per column.",
        "get_descriptive_stats": "Returns basic statistics for numeric columns.",
        "get_value_counts": "Returns value counts for a column.",
        "get_class_imbalance": "Returns class distribution for a target column.",
        "get_correlation_matrix": "Returns correlations between numeric columns.",
        "get_target_correlation": "Returns correlations with a target column.",
        "get_group_target_analysis": "Returns mean target value by group.",
        "detect_outliers_iqr": "Detects outliers in a numeric column.",
        "plot_histogram": "Plots a histogram for a column.",
        "plot_correlation_heatmap": "Plots a correlation heatmap.",
        "plot_group_target": "Plots mean target by group.",
        "plot_boxplot": "Plots a boxplot for a column.",
        "get_preprocessing_recommendations": "Returns preprocessing recommendations."
    },
    "current": {
        "get_shape": "Use this first. Returns the number of rows and columns in the dataset.",
        "get_missing_values": "Returns count and percentage of missing values for each column.",
        "get_dtypes": "Returns the data type of each column in the dataset.",
        "get_cardinality": "Returns the number of unique values in each column.",
        "get_descriptive_stats": "Returns descriptive statistics like mean, std, min, max for numeric columns.",
        "get_value_counts": "Returns value counts for a specific column. Input must be a column name.",
        "get_class_imbalance": "Returns class distribution and imbalance ratio for a target column. Input must be a column name.",
        "get_correlation_matrix": "Returns the correlation matrix for all numeric columns.",
        "get_target_correlation": "Returns correlation of all numeric columns with a target column. Input must be a column name.",
        "get_group_target_analysis": "Returns mean target value grouped by a categorical column. Input format: 'group_col,target_col'",
        "detect_outliers_iqr": "Detects outliers in a numeric column using IQR method. Input must be a column name.",
        "plot_histogram": "Plots a histogram for a numeric column. Input must be a column name.",
        "plot_correlation_heatmap": "Plots a heatmap of the correlation matrix for numeric columns.",
        "plot_group_target": "Plots mean target value by group as a bar chart. Input format: 'group_col,target_col'",
        "plot_boxplot": "Plots a boxplot for a numeric column. Input must be a column name.",
        "get_preprocessing_recommendations": "Analyzes the dataset and returns preprocessing recommendations."
    },
    "enhanced": {
        "get_shape": "Use this tool when the user asks about the size, shape, or structure of the dataset. Returns the number of rows and columns, giving the analyst a foundational understanding of data scale before deeper analysis. After calling this tool, proceed with get_missing_values to assess data quality.",
        "get_missing_values": "Use this tool when the user asks about missing data, null values, or data completeness. This tool analyses every column in the dataset and returns the exact count of missing values alongside the percentage of total rows affected. Use the results to identify which columns need imputation or dropping before any analysis or modelling. Always call get_dtypes after this tool to determine the appropriate imputation strategy for each column.",
        "get_dtypes": "Use this tool when the user asks about column types or data structure. Returns the data type of each column such as int, float, or object, helping the analyst determine appropriate analysis methods — numeric columns suit statistical analysis while object columns require encoding or grouping. After this tool, proceed with get_cardinality to understand value distributions.",
        "get_cardinality": "Use this tool to understand the diversity of values in each column. Returns the count of unique values, helping the analyst identify high cardinality columns that may need target or frequency encoding, binary columns suitable for label encoding, and potential ID columns that should be dropped. After this tool, proceed with get_value_counts for columns with low cardinality to understand their distributions.",
        "get_descriptive_stats": "Use this tool when the user asks about distributions, ranges, averages, or statistical summaries of numeric data. Returns mean, standard deviation, min, max, and quartiles for all numeric columns, helping the analyst identify skewed distributions, unexpected ranges, and potential outliers. After this tool, proceed with detect_outliers_iqr to formally test for outliers in columns with suspicious ranges.",
        "get_value_counts": "Use this tool when the user asks about the distribution of values in a specific categorical column. Returns the frequency of each unique value, helping the analyst understand category distributions and spot dominant or rare categories. Use after get_cardinality identifies low cardinality columns worth exploring. Input must be a valid column name.",
        "get_class_imbalance": "Use this tool when the user asks about target variable balance, class distribution, or dataset bias. Returns the count and percentage of each class in the target column, helping the analyst identify severe imbalance that may require resampling or weighted loss functions during modelling. Input must be the target column name. After this tool, proceed with get_target_correlation to understand which features drive the target.",
        "get_correlation_matrix": "Use this tool when the user asks about relationships between numeric features or multicollinearity concerns. Returns a full pairwise correlation matrix for all numeric columns, helping the analyst identify strongly correlated feature pairs that may cause redundancy in modelling. After this tool, proceed with plot_correlation_heatmap to visualise the matrix for easier interpretation.",
        "get_target_correlation": "Use this tool when the user asks which features are most predictive of or related to the target variable. Returns the correlation coefficient of every numeric column with the specified target, sorted by strength, helping the analyst prioritise features for modelling. Input must be the target column name. After this tool, proceed with get_group_target_analysis to explore how categorical features relate to the target.",
        "get_group_target_analysis": "Use this tool when the user asks how a categorical feature relates to the target variable, or wants to understand group-level differences in the target. Returns the mean target value for each category in the grouping column, helping the analyst identify which categories are associated with higher or lower target values. Input must be two comma-separated column names in the format 'group_col,target_col'. After this tool, proceed with plot_group_target to visualise the group differences.",
        "detect_outliers_iqr": "Use this tool when the user asks about anomalies, extreme values, or outliers in a specific numeric column. Uses the interquartile range method to identify values below Q1-1.5xIQR or above Q3+1.5xIQR, returning the count and percentage of outlier rows. Helps the analyst decide whether to cap, remove, or investigate extreme values before modelling. Input must be a numeric column name. After this tool, proceed with plot_boxplot to visualise the outlier distribution.",
        "plot_histogram": "Use this tool when the user asks to visualise the distribution of a numeric column. Returns a histogram showing the frequency of value ranges, helping the analyst identify skewness, modality, and distribution shape. Use after get_descriptive_stats to visually confirm statistical summaries. Input must be a numeric column name.",
        "plot_correlation_heatmap": "Use this tool when the user asks to visualise relationships between numeric features. Returns a colour-coded heatmap of the full correlation matrix, making it easier to spot strongly correlated feature pairs than reading raw numbers. Use after get_correlation_matrix to provide a visual complement to the numeric output. No input required.",
        "plot_group_target": "Use this tool when the user asks to visualise how a categorical feature relates to the target variable. Returns a bar chart showing mean target value for each category, making group differences immediately interpretable. Use after get_group_target_analysis to visually confirm numeric findings. Input must be two comma-separated column names in the format 'group_col,target_col'.",
        "plot_boxplot": "Use this tool when the user asks to visualise the spread, quartiles, or outliers of a numeric column. Returns a boxplot showing the median, interquartile range, and outlier points, giving the analyst a complete picture of value distribution. Use after detect_outliers_iqr to visually confirm numeric outlier findings. Input must be a numeric column name.",
        "get_preprocessing_recommendations": "Use this tool when the user asks what preprocessing steps are needed before modelling, or requests a data cleaning plan. Analyses the full dataset and returns specific recommendations for each column covering missing value imputation strategies, outlier handling, and encoding approaches for categorical variables. Use after get_missing_values, get_dtypes, and detect_outliers_iqr to provide context for the recommendations. No input required."
    }
}
